server:
  address: ":8000"
  dumpRouterMap: true
  routeOverWrite: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "info"
  stdout: true

database:
  logger:
    level: "all"
    stdout: true
  default:
    type: "mysql"
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/itcodex?loc=Local&parseTime=true&charset=utf8mb4"
    debug: true
    createdAt: "created_at"
    updatedAt: "updated_at"

metadata:
  dsn: "root:123456@tcp(127.0.0.1:3306)/itcodex?parseTime=true&loc=Local&charset=utf8mb4"
  tablePrefix: "c_"
  autoSync: true
  scriptsPath: "./manifest/scripts"
  scriptTimeout: 5000
  defaultPrimaryKey: "snowflake"
  allowTruncate: false
  logging: true
