// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"itcodex/server/internal/dao/internal"
)

// collectionsDao is the data access object for the table c_collections.
// You can define custom methods on it to extend its functionality as needed.
type collectionsDao struct {
	*internal.CollectionsDao
}

var (
	// Collections is a globally accessible object for table c_collections operations.
	Collections = collectionsDao{internal.NewCollectionsDao()}
)

// Add your custom methods and functionality below.
