// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"itcodex/server/internal/dao/internal"
)

// fieldsDao is the data access object for the table c_fields.
// You can define custom methods on it to extend its functionality as needed.
type fieldsDao struct {
	*internal.FieldsDao
}

var (
	// Fields is a globally accessible object for table c_fields operations.
	Fields = fieldsDao{internal.NewFieldsDao()}
)

// Add your custom methods and functionality below.
