// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"itcodex/server/internal/dao/internal"
)

// indexesDao is the data access object for the table c_indexes.
// You can define custom methods on it to extend its functionality as needed.
type indexesDao struct {
	*internal.IndexesDao
}

var (
	// Indexes is a globally accessible object for table c_indexes operations.
	Indexes = indexesDao{internal.NewIndexesDao()}
)

// Add your custom methods and functionality below.
