// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"itcodex/server/internal/dao/internal"
)

// yaegiScriptsDao is the data access object for the table c_yaegi_scripts.
// You can define custom methods on it to extend its functionality as needed.
type yaegiScriptsDao struct {
	*internal.YaegiScriptsDao
}

var (
	// YaegiScripts is a globally accessible object for table c_yaegi_scripts operations.
	YaegiScripts = yaegiScriptsDao{internal.NewYaegiScriptsDao()}
)

// Add your custom methods and functionality below.
